# Generated by Django 5.0.4 on 2024-04-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickcounter',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
